### ISSUE TITLE
Error thrown when getAllMeasures() returns 0-length array

### ISSUE THREAD

**Issue by monte-hayward** [havasnewyork/nycschoolfinder#1]
This passage of code assumes a non-empty array:
dojoldxModmt.js
      getInOrOutMeasure: function(a) {
                        return this.getAllMeasures().first(function(c) {
                            return c.getKey() == a
                        }
                        )
                    },
The error is thrown after the personality insights service has produced results, and before tradeoffs are displayed.
A dump of "this" in scope here:
r…e.c…e.d…e.b {id: "View_1", scenario: r…e.c…e.d…e.b, name: "Top options", description: "Top options", _allSolutions: Array[4]…}_allSolutions: Array[4]_currentSolDecorator: null_filters: Object_inMeasures: Array[0]_nextSolDecorator: null_outMeasures: Array[0]_solFilterCounter: Objectconns: Array[0]description: "Top options"filtrateChanged: ()id: "View_1"measuresChanged: ()name: "Top options"perspective: require.cache.dojo/_base/declare.bscenario: require.cache.dojo/_base/declare.bsolutionsChanged: ()__proto__: require.cache.dojo/_base/declare.b

This error is reproducible with some random thing that I wrote, as well as with the Gettysburg Address, copied from here:  http://www.abrahamlincolnonline.org/lincoln/speeches/gettysburg.htm

Uncaught TypeError: Cannot read property 'getKey' of null(anonymous function) @ dojoIdxModmt.js:1174require.cache.dojo/_base/array.e.forEach @ dojoIdxModmt.js:44require.cache.modmt/sommos/SommosWidget.d.declare.drawLabels @ dojoIdxModmt.js:1173require.cache.modmt/sommos/SommosWidget.d.declare.render @ dojoIdxModmt.js:1168require.cache.modmt/sommos/SommosWidget.d.declare.bind @ dojoIdxModmt.js:1167(anonymous function) @ dojoIdxModmt.js:448require.cache.modmt/moov/ExplorePane.d.declare.viewChanged @ dojoIdxModmt.js:448require.cache.modmt/moov/ExplorePane.d.declare.bindToFront @ dojoIdxModmt.js:445require.cache.modmt/moov/MOOVWidget.d.declare._show @ dojoIdxModmt.js:212require.cache.modmt/moov/MOOVWidget.d.declare.showByDto_dontRefreshQuestionBar @ dojoIdxModmt.js:209require.cache.modmt/moov/MOOVWidget.d.declare.showDilemma @ dojoIdxModmt.js:209(anonymous function) @ dojoIdxModmt.js:209require.cache.modmt/proxy/IframeParentJsonProxy.d.declare.receiveMessage @ dojoIdxModmt.js:1347require.cache.dojo/_base/lang.e.hitch @ dojoIdxModmt.js:40

d.forEach(b.anchors, function(a, b) {
                            var d = 
                            this.view.getInOrOutMeasure(a.objectiveKey)
                              , e = this.anchors[d.getKey()]
                              , h = modmt.draw.angle(k, e)
                              , m = modmt.draw.xyDistance(k, e) + modmt.eval(l.anchor.wireLabelGlyphRatio) \* c
                              , m = modmt.draw.getCirclePointCW(k, m, h);
                            this.labelsGroup.createPath().moveTo(e.x, e.y).lineTo(m.x, m.y).setStroke(modmt.eval(l.stroke));
                            e = this.createObjectiveLabel(d, l);
                            this.locateRelative(e, m, h, {
                                dx: 12,
                                dy: 0
                            });
                            this.labels[d.getKey()] = e;
                            this.joints[d.getKey()] = m
                        }
                        , this)

**Comment by splatcollision** [comment]
Hi Monte - 

Thanks very much for this bug report! Looks like an issue with the Tradeoff Analytics frontend code, so I will pass this along to the IBM teams that developed that. However looking at the sample results from the Gettysburg address, it looks like sometimes some schools are being recommended without having a complete set of data for the tradeoff code - this might be the root cause. I'll look into this soon!

Thanks, Kevin

**Comment by germanattanasio** [comment]
@boazdavid this looks like an issue in the TA front-end code. Can you take a look?

**Comment by boazdavid** [comment]
Seems that your app is now bound to a new service instance of a 'standard' plan (was 'free'). That is, moved from beta to GA service. 
An equivalent change should be done when referring the frontend library. you should change the script src to: http://ta-cdn.mybluemix.net/v1/TradeoffAnalytics.js (note the /v1 part). 
see also http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tradeoff-analytics/upgrade.shtml.
In addition, please change in 'ui.js' to:
customCssUrl: 'https://ta-cdn.mybluemix.net/v1/modmt/styles/watson.css',

regards, David

**Comment by germanattanasio** [comment]
Thanks david!

**Comment by splatcollision** [comment]
David, German - Thanks for the pointers. Glad it was easy as that! 

d8984b474de9106acc5b77ad531e14f5a86915aa has the fixes, and the public bluemix app has also been updated.
